//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenRight
    {
        public int ScreenRightId { get; set; }
        public string ScreenRightName { get; set; }
        public Nullable<int> ScreenId { get; set; }
    }
}
