//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InventoryTransaction
    {
        public int Id { get; set; }
        public Nullable<int> RefDocumentTypeId { get; set; }
        public Nullable<int> RefDocIdNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> SupplierCustomerId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<double> QtyIn { get; set; }
        public Nullable<double> QtyOut { get; set; }
        public Nullable<double> ItemRate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_Item_Allocation tbl_Item_Allocation { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblSupplierCustomer tblSupplierCustomer { get; set; }
    }
}
