//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item_Allocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Item_Allocation()
        {
            this.tbl_InventoryTransaction = new HashSet<tbl_InventoryTransaction>();
            this.tbl_PurchaseDetail = new HashSet<tbl_PurchaseDetail>();
            this.tbl_PurchaseReturnDetail = new HashSet<tbl_PurchaseReturnDetail>();
            this.tbl_SaleDetail = new HashSet<tbl_SaleDetail>();
            this.tbl_SaleReturnDetail = new HashSet<tbl_SaleReturnDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> PurchaseAccount { get; set; }
        public Nullable<int> SaleAccount { get; set; }
        public Nullable<int> COGSGLAC { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Entry_User { get; set; }
        public Nullable<int> Modify_User { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InventoryTransaction> tbl_InventoryTransaction { get; set; }
        public virtual tbl_Item_Def tbl_Item_Def { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCOA tblCOA { get; set; }
        public virtual tblCOA tblCOA1 { get; set; }
        public virtual tblCOA tblCOA2 { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseDetail> tbl_PurchaseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseReturnDetail> tbl_PurchaseReturnDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleDetail> tbl_SaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleReturnDetail> tbl_SaleReturnDetail { get; set; }
    }
}
