//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SaleMaster()
        {
            this.tbl_SaleDetail = new HashSet<tbl_SaleDetail>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> SupplierCustomerId { get; set; }
        public string ManualBillNo { get; set; }
        public Nullable<double> BillAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Entry_User { get; set; }
        public Nullable<int> Modify_User { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleDetail> tbl_SaleDetail { get; set; }
        public virtual tbl_SaleMaster tbl_SaleMaster1 { get; set; }
        public virtual tbl_SaleMaster tbl_SaleMaster2 { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblDocumentType tblDocumentType { get; set; }
        public virtual tblSupplierCustomer tblSupplierCustomer { get; set; }
    }
}
