//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item_Def
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Item_Def()
        {
            this.tbl_Item_Allocation = new HashSet<tbl_Item_Allocation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> PackQty { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Allocation> tbl_Item_Allocation { get; set; }
        public virtual tblCategory tblCategory { get; set; }
    }
}
