//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityLog
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Activity { get; set; }
        public string Screen_Name { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
