//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBranch()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.tbl_Item_Allocation = new HashSet<tbl_Item_Allocation>();
            this.tbl_PurchaseMaster = new HashSet<tbl_PurchaseMaster>();
            this.tbl_PurchaseReturnMaster = new HashSet<tbl_PurchaseReturnMaster>();
            this.tbl_SaleMaster = new HashSet<tbl_SaleMaster>();
            this.tbl_SaleReturnMaster = new HashSet<tbl_SaleReturnMaster>();
            this.tblCOAs = new HashSet<tblCOA>();
            this.tblCOAOpeningBalances = new HashSet<tblCOAOpeningBalance>();
            this.tblSubAccounts = new HashSet<tblSubAccount>();
            this.tblSupplierCustomers = new HashSet<tblSupplierCustomer>();
            this.tblVoucherHeads = new HashSet<tblVoucherHead>();
        }
    
        public int Id { get; set; }
        public string Branch_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contact_No { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Entry_User { get; set; }
        public Nullable<int> Modify_User { get; set; }
        public Nullable<int> Company_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item_Allocation> tbl_Item_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseMaster> tbl_PurchaseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseReturnMaster> tbl_PurchaseReturnMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleMaster> tbl_SaleMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleReturnMaster> tbl_SaleReturnMaster { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCOA> tblCOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCOAOpeningBalance> tblCOAOpeningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubAccount> tblSubAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierCustomer> tblSupplierCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherHead> tblVoucherHeads { get; set; }
    }
}
