//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCOAOpeningBalance
    {
        public int Id { get; set; }
        public Nullable<int> COA_Id { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Entry_User { get; set; }
        public Nullable<int> Modify_User { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCOA tblCOA { get; set; }
        public virtual tblCompany tblCompany { get; set; }
    }
}
