//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOPD
    {
        public int Id { get; set; }
        public Nullable<int> Dr_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<double> Fees { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> Token_No { get; set; }
        public Nullable<bool> Visited { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    
        public virtual tblCOA tblCOA { get; set; }
        public virtual tblSupplierCustomer tblSupplierCustomer { get; set; }
    }
}
