//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupplierCustomer()
        {
            this.tbl_InventoryTransaction = new HashSet<tbl_InventoryTransaction>();
            this.tbl_PurchaseMaster = new HashSet<tbl_PurchaseMaster>();
            this.tbl_PurchaseReturnMaster = new HashSet<tbl_PurchaseReturnMaster>();
            this.tbl_SaleMaster = new HashSet<tbl_SaleMaster>();
            this.tbl_SaleReturnMaster = new HashSet<tbl_SaleReturnMaster>();
            this.tblOPDs = new HashSet<tblOPD>();
        }
    
        public int Id { get; set; }
        public string Profile_Name { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string Reporting_Title { get; set; }
        public Nullable<int> GlAccount_Id { get; set; }
        public string SupplierCustomerType { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<int> Entry_User { get; set; }
        public Nullable<int> Modify_User { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InventoryTransaction> tbl_InventoryTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseMaster> tbl_PurchaseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseReturnMaster> tbl_PurchaseReturnMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleMaster> tbl_SaleMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleReturnMaster> tbl_SaleReturnMaster { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCOA tblCOA { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOPD> tblOPDs { get; set; }
    }
}
