//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDetail
    {
        public int Id { get; set; }
        public Nullable<int> Voucher_Head_Id { get; set; }
        public Nullable<int> COA_Id { get; set; }
        public Nullable<int> Against_COA_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<double> DebitAmount { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public string ChequeNo { get; set; }
    
        public virtual tblVoucherHead tblVoucherHead { get; set; }
    }
}
